version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
      - POSTGRES_USER=db
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
